### ISSUE TITLE
iOS app?

### ISSUE THREAD

**Issue by bellebethcooper** [melissamcewen/CurlsBotSite#3]
Hi! I couldn't find a way to contact you outside Facebook, which I don't use, so hopefully an issue is okay!

I'm a mobile dev and was thinking an iOS app version of CurlsBot might be handy. I think if it had a share extension, it would be possible to copy some text from a shop website, then use the share extension to send it to CurlsBot to analyse. I haven't looked into action extensions, but that might even make it faster/easier too.

I wanted to check how you feel about the idea of a mobile app? I could just make something separate without connecting it to CurlsBot at all, but since you've open-sourced the code and already worked on the logic for analysing ingredients, etc. I thought it made sense to check in with you first in case you'd prefer to be involved and have it connected to the CurlsBot project. No pressure either way, just wanted to float the idea!

**Comment by rindoza** [comment]
Please let me know if you need my help, I'd love to assist.

**Comment by melissamcewen** [comment]
Hi @bellebethcooper would love the help, I'm going to probably make an API at some point so that would definitely make it soooooooooooo much easier. Right now it's a Progressive Web App but that has a lot of limitations esp on iOS. Everyone who wants to help the best way to contact me is actually Twitter https://twitter.com/melissamcewen or my email which is on http://melissamcewen.com/

**Comment by bellebethcooper** [comment]
@melissamcewen Ooh yes, an API would make a huge difference. I'll check back in when the API is up and running then :)
